### ISSUE TITLE
Skills should have names

### ISSUE THREAD

**Issue by sagar-io** [priyankarpal/Portfolio#16]
In the skill section, Non-technical individuals(like HR) can't predict the name of the skill by just seeing the icon. 
So, each skill should have a tooltip/title to show its name like "Tailwind CSS" .

![Screenshot 2023-04-20 134340](https://user-images.githubusercontent.com/86215447/233304015-def82607-925d-4660-a30d-d141afa183ee.png)

**Comment by sagar-io** [comment]
Hey @priyankarpal, I want to resolve this issue.

**Comment by priyankarpal** [comment]
good idea 💡. You can work on it
