### ISSUE TITLE
feat: multipage portfolio

### ISSUE THREAD

**Issue by sagar-io** [priyankarpal/Portfolio#22]
As the projects and experiences sections will grow with time then It'll be **difficult to navigate** the site so a multipage approach is needed.

_See -_ 
![Screenshot 2023-04-22 234901](https://user-images.githubusercontent.com/86215447/233800635-e691ea0e-14b2-479f-bef5-a7e01ab96498.jpg)

For this, we can use React Router.

**Comment by priyankarpal** [comment]
could you elaborate a little bit?

**Comment by sagar-io** [comment]
Yeah! Currently, we have the introduction section, projects section, skills section and experience section on a single page. 
By the time, it'll become messy to have all the projects and experiences listed on one page so if a user only wants to see the experience section then he has to scroll all the way to the bottom.

Instead, we can use a navigation bar (see the example image in my previous comment) and present all the sections (project, skills, experience, etc) on different pages. By just clicking any of the navigation bar links users can navigate to their desirable page. 

and here we're not using simple HTML/CSS/JS where the browser has to reload the website to navigate to different pages. we're using React which is mostly for single-page applications so our browser will treat our application as a single-page application and will not reload while navigating different pages. For this React Router is an appropriate choice. If you're not familiar with React Router then you can check - [React Router](https://reactrouter.com/en/main).

**Comment by priyankarpal** [comment]
> Yeah! Currently, we have the introduction section, projects section, skills section and experience section on a single page. By the time, it'll become messy to have all the projects and experiences listed on one page so if a user only wants to see the experience section then he has to scroll all the way to the bottom.
> 
> Instead, we can use a navigation bar (see the example image in my previous comment) and present all the sections (project, skills, experience, etc) on different pages. By just clicking any of the navigation bar links users can navigate to their desirable page.
> 
> and here we're not using simple HTML/CSS/JS where the browser has to reload the website to navigate to different pages. we're using React which is mostly for single-page applications so our browser will treat our application as a single-page application and will not reload while navigating different pages. For this React Router is an appropriate choice. If you're not familiar with React Router then you can check - [React Router](https://reactrouter.com/en/main).

yes. I understand. We can do it. Also, I have a knowledge of Reactjs  😅
