### ISSUE TITLE
Favicon isn't properly visible

### ISSUE THREAD

**Issue by sagar-io** [priyankarpal/Portfolio#23]
Because of the small size of the favicon (mostly, _16×16 pixels_), the **visibility** of a person's images as a favicon becomes **poor** so the favicon should be updated with a new logo or icon that can be visible even in small size.

For example, we should use these types of icons in the favicon - 
![Screenshot 2023-04-23 003952](https://user-images.githubusercontent.com/86215447/233802391-4ee6041f-4545-4579-8cf9-49dafd402c32.jpg)

**Comment by priyankarpal** [comment]
these are icons related to business or something else. BUt what's if we use another icons related to coding

**Comment by sagar-io** [comment]
Yeah, totally fine. They're just examples.

**Comment by priyankarpal** [comment]
> Yeah, totally fine. They're just examples.

ok then add favicon

**Comment by priyankarpal** [comment]
assigning to you
