### ISSUE TITLE
feat: 'contact us form' should be present on portfolio 

### ISSUE THREAD

**Issue by sagar-io** [priyankarpal/Portfolio#24]
Letting the **Recruiter communicate** with you by **email** is necessary but simply putting your email address on your portfolio is not a good practice. 
Instead, Putting a contact us page on the portfolio shows your recruiter that you’re well organized and invested time in getting in touch with them in a better way and it'll not reveal the email address to scammers.

_See -_
![sd](https://user-images.githubusercontent.com/86215447/233802866-35b0e7c8-350c-40f0-bed7-0a488c0f5304.png)

A portfolio that has a decent and clear contact form looks more **professional** and **appealing**.

**Comment by priyankarpal** [comment]
ok ok assigning to you
