### ISSUE TITLE
Maybe updating read me file 

### ISSUE THREAD

**Issue by agatha-chituwa** [priyankarpal/Portfolio#30]
as someone who has never used pnpm package before i had hard time, i feel like some steps were missed like installing globally npm install -g pnpm. and on some machines you need to allow scripts to run

**Comment by priyankarpal** [comment]
> as someone who has never used pnpm package before i had hard time, i feel like some steps were missed like installing globally npm install -g pnpm. and on some machines you need to allow scripts to run

do you want to work on it?

**Comment by agatha-chituwa** [comment]
Yes, I will work on it
