### ISSUE TITLE
fix: remove line-clamp for mobile view

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/Portfolio#32]
- Here we need to remove the line clamp  for the mobile view

![image](https://user-images.githubusercontent.com/88102392/235618420-7d5a9631-8bb7-4d72-9d5b-0a9530e58063.png)

**Comment by mhdamaan79** [comment]
Hey Priyankarpal, can I work on this issue

**Comment by mhdamaan79** [comment]
I removed the line clamp for the mobile view 👇


![Screenshot 2023-05-02 145914](https://user-images.githubusercontent.com/118375524/235631486-fb1c65d2-82a4-4325-a7f0-7d8c49dc4138.png)

**Comment by priyankarpal** [comment]
> Hey Priyankarpal, can I work on this issue

assigned to you
