### ISSUE TITLE
feat:  add contribution url & text to the footer

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/Portfolio#7]
- We need to add a `contribute here` link to the footer 
- https://github.com/priyankarpal/Portfolio

**Comment by jayk-gupta** [comment]
Can I work on it?

**Comment by priyankarpal** [comment]
> Can I work on it?

sounds good 🎉

**Comment by priyankarpal** [comment]
> Can I work on it?

You can work on it 🤝

**Comment by jayk-gupta** [comment]
okay
